import type {
  BankAccount,
  Movement,
  Goal,
  ExpenseNature,
  CreditCardItem,
  PaymentMethodItem,
  BankInstitution,
  SalaryContract,
} from '../types';

export const DEMO_BANKS: BankInstitution[] = [
  { id: 'bank_nubank', name: 'Nubank S.A.', code: '260', color: '#8A05BE', icon: '🟣', status: 'CONECTADO', syncedAt: 'há 12 minutos' },
  { id: 'bank_inter', name: 'Banco Inter', code: '077', color: '#FF7A00', icon: '🟠', status: 'CONECTADO', syncedAt: 'há 1 hora' },
  { id: 'bank_xp', name: 'XP Investimentos', code: '102', color: '#1E293B', icon: '⚪', status: 'CONECTADO', syncedAt: 'há 4 horas' },
  { id: 'bank_caixa', name: 'Caixa Econômica', code: '104', color: '#0066B3', icon: '🔵', status: 'MANUAL', syncedAt: 'Manual' },
];

export const DEMO_SALARY_CONTRACTS: SalaryContract[] = [
  {
    id: 'sal_clt_tech',
    employer: 'Tech Inovação & Soluções S.A.',
    role: 'Especialista de Sistemas & Tech Lead',
    contractType: 'CLT',
    paymentDay: 5,
    secondPaymentDay: 20,
    currentGrossAmount: 12000.00,
    currentNetAmount: 8963.68,
    receivingBankAccountId: 'acc_inter',
    receivingBankName: 'Banco Inter',
    startDate: '2024-03-01',
    isActive: true,
    history: [
      {
        id: 'adj_1',
        effectiveDate: '2024-03',
        grossAmount: 9000.00,
        netAmount: 7150.00,
        percentageIncrease: 0,
        reason: 'OUTRO',
        title: 'Admissão Inicial (Pleno)',
        notes: 'Início do contrato de trabalho CLT',
      },
      {
        id: 'adj_2',
        effectiveDate: '2025-05',
        grossAmount: 10500.00,
        netAmount: 8120.00,
        percentageIncrease: 13.57,
        reason: 'DISSÍDIO_CONVENÇÃO',
        title: 'Dissídio e Acordo Coletivo 2025',
        notes: 'Reajuste anual sindical da categoria de Tecnologia da Informação',
      },
      {
        id: 'adj_3',
        effectiveDate: '2026-02',
        grossAmount: 12000.00,
        netAmount: 8963.68,
        percentageIncrease: 10.39,
        reason: 'MÉRITO',
        title: 'Promoção para Especialista Tech Lead',
        notes: 'Reconhecimento por liderança técnica e entrega do novo core financeiro',
      },
    ],
  },
];

export const DEMO_ACCOUNTS: BankAccount[] = [
  { id: 'acc_nubank', name: 'Nubank Principal', bankName: 'Nubank S.A.', type: 'CORRENTE', balance: 14250.00, color: '#8A05BE', icon: '🟣' },
  { id: 'acc_inter', name: 'Inter Conta Digital', bankName: 'Banco Inter', type: 'CORRENTE', balance: 10550.00, color: '#FF7A00', icon: '🟠' },
  { id: 'acc_xp', name: 'XP Carteira Global', bankName: 'XP Investimentos', type: 'INVESTIMENTO', balance: 732700.00, color: '#1E293B', icon: '⚪' },
  { id: 'acc_reserva', name: 'Tesouro Selic (Reserva)', bankName: 'Inter', type: 'POUPANCA', balance: 85000.00, color: '#10B981', icon: '🟢' },
];

export const DEMO_CARDS: CreditCardItem[] = [
  {
    id: 'card_nubank_black',
    name: 'Nubank Mastercard Black',
    bank: 'Nubank S.A.',
    brand: 'MASTERCARD',
    limitTotal: 35000.00,
    limitUsed: 5420.00,
    closingDay: 28,
    dueDay: 5,
    color: '#8A05BE',
  },
  {
    id: 'card_xp_infinite',
    name: 'XP Visa Infinite',
    bank: 'XP Investimentos',
    brand: 'VISA',
    limitTotal: 50000.00,
    limitUsed: 3100.00,
    closingDay: 20,
    dueDay: 28,
    color: '#0F172A',
  },
];

export const DEMO_PAYMENT_METHODS: PaymentMethodItem[] = [
  { id: 'pm_pix_nubank', name: 'PIX (Nubank)', type: 'PIX', linkedAccountId: 'acc_nubank', icon: '⚡', color: '#00D2B6' },
  { id: 'pm_card_nubank', name: 'Cartão Nubank Black', type: 'CARTAO_CREDITO', linkedCardId: 'card_nubank_black', icon: '💳', color: '#8A05BE' },
  { id: 'pm_card_xp', name: 'Cartão XP Infinite', type: 'CARTAO_CREDITO', linkedCardId: 'card_xp_infinite', icon: '💳', color: '#38BDF8' },
  { id: 'pm_debito_inter', name: 'Débito em Conta (Inter)', type: 'CARTAO_DEBITO', linkedAccountId: 'acc_inter', icon: '🏧', color: '#FF7A00' },
  { id: 'pm_boleto', name: 'Boleto Bancário', type: 'BOLETO', icon: '📄', color: '#F59E0B' },
  { id: 'pm_dinheiro', name: 'Dinheiro em Espécie', type: 'DINHEIRO', icon: '💵', color: '#10B981' },
];

export const DEMO_MOVEMENTS: Movement[] = [
  {
    id: 'rec_1',
    title: 'Salário (1ª Quinzena CLT)',
    type: 'RECEBER',
    amount: 8500.00,
    dueDate: '2026-10-05',
    bank: 'Inter',
    status: 'PREVISTA',
    category: 'Salário',
    notes: 'Adiantamento mensal líquido',
  },
  {
    id: 'rec_2',
    title: 'Dividendos & Proventos B3',
    type: 'RECEBER',
    amount: 1450.00,
    dueDate: '2026-10-15',
    bank: 'XP',
    status: 'PREVISTA',
    category: 'Investimentos',
    notes: 'Rendimento de FIIs e Ações',
  },
  {
    id: 'rec_3',
    title: 'Consultoria Estratégica',
    type: 'RECEBER',
    amount: 5700.00,
    dueDate: '2026-10-22',
    bank: 'Nubank',
    status: 'PREVISTA',
    category: 'Serviços',
    notes: 'Honorário de projeto avulso',
  },
  {
    id: 'pay_1',
    title: 'Condomínio & Manutenção',
    type: 'PAGAR',
    amount: 1250.00,
    dueDate: '2026-10-08',
    bank: 'Nubank',
    status: 'PREVISTA',
    category: 'Moradia',
    notes: 'Taxa condominial residencial',
  },
  {
    id: 'pay_2',
    title: 'Escola / Educação Filhos',
    type: 'PAGAR',
    amount: 2850.00,
    dueDate: '2026-10-10',
    bank: 'Inter',
    status: 'PREVISTA',
    category: 'Educação',
    notes: 'Mensalidade escolar',
  },
  {
    id: 'pay_3',
    title: 'Plano de Saúde Familiar',
    type: 'PAGAR',
    amount: 1680.00,
    dueDate: '2026-10-12',
    bank: 'Nubank',
    status: 'PREVISTA',
    category: 'Saúde',
    notes: 'Cobertura médica ampla',
  },
  {
    id: 'pay_4',
    title: 'Energia Elétrica (Coelba)',
    type: 'PAGAR',
    amount: 420.00,
    dueDate: '2026-10-16',
    bank: 'Caixa',
    status: 'PREVISTA',
    category: 'Utilidades',
    notes: 'Consumo do mês',
  },
  ...[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18].map((num, idx) => {
    const year = 2026 + Math.floor((9 + idx) / 12);
    const month = ((9 + idx) % 12) + 1;
    const monthStr = month < 10 ? `0${month}` : `${month}`;
    return {
      id: `lia_inter_${num}`,
      title: `Parcela Empréstimo Consignado (${num}/18)`,
      type: 'EMPRESTIMO' as const,
      amount: 1458.51,
      dueDate: `${year}-${monthStr}-10`,
      bank: 'Inter',
      status: 'PREVISTA' as const,
      category: 'Empréstimos',
      notes: `Parcela ${num} de 18 (Taxa 3.03% a.m.)`,
      installmentNumber: num,
      installmentsTotal: 18,
      installmentGroupId: 'group_consignado_inter',
      interestRatePercent: 3.03,
    };
  }),
  {
    id: 'cc_1',
    title: 'Fatura Nubank Mastercard Black',
    type: 'CARTAO',
    amount: 3850.00,
    dueDate: '2026-10-06',
    bank: 'Nubank',
    status: 'PREVISTA',
    category: 'Cartão de Crédito',
    notes: 'Gastos recorrentes e mercado',
  },
  {
    id: 'cc_2',
    title: 'Fatura XP Visa Infinite',
    type: 'CARTAO',
    amount: 1260.00,
    dueDate: '2026-10-15',
    bank: 'XP',
    status: 'PREVISTA',
    category: 'Cartão de Crédito',
    notes: 'Viagens e lazer',
  },
  {
    id: 'real_1',
    title: 'Supermercado Mensal',
    type: 'PAGAR',
    amount: 680.00,
    dueDate: '2026-09-12',
    bank: 'Nubank',
    status: 'REALIZADA',
    category: 'Alimentação',
    notes: 'Pago no débito',
  },
  {
    id: 'real_2',
    title: 'Adiantamento de Projeto',
    type: 'RECEBER',
    amount: 3200.00,
    dueDate: '2026-09-10',
    bank: 'Inter',
    status: 'REALIZADA',
    category: 'Serviços',
    notes: 'PIX compensado',
  },
];

export const DEMO_GOALS: Goal[] = [
  {
    id: 'goal_1',
    title: 'Reserva de Emergência (8 Meses)',
    category: 'Segurança',
    currentAmount: 85000,
    targetAmount: 100000,
    monthlyContribution: 2500,
    targetDate: 'Dezembro de 2026',
    icon: '🛡️',
    color: '#10B981',
  },
  {
    id: 'goal_2',
    title: 'Quitação Antecipada do Empréstimo',
    category: 'Desendividamento',
    currentAmount: 12000,
    targetAmount: 17367,
    monthlyContribution: 1800,
    targetDate: 'Março de 2027',
    icon: '⚡',
    color: '#38BDF8',
  },
  {
    id: 'goal_3',
    title: 'Aporte de Independência Financeira',
    category: 'Liberdade',
    currentAmount: 645500,
    targetAmount: 1200000,
    monthlyContribution: 4000,
    targetDate: 'Outubro de 2031',
    icon: '🏛️',
    color: '#A855F7',
  },
];

export const DEMO_NATURES: ExpenseNature[] = [
  {
    id: 'nat_alimentacao',
    name: 'Alimentação & Mercado',
    color: '#10B981',
    icon: '🛒',
    type: 'ESSENCIAL',
    description: 'Gastos de sobrevivência alimentar: supermercado mensal, feira livre e açougue.',
    overCeilingJustification: '',
    justificationHistory: [],
    keywords: ['mercado', 'supermercado', 'feira', 'hortifruti', 'acougue', 'padaria', 'ifood', 'compras'],
    mappings: [
      {
        id: 'map_mercado_mensal',
        name: 'Supermercado Base Mensal (Estoque Seco & Limpeza)',
        natureId: 'nat_alimentacao',
        applicableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        frequency: 'MENSAL',
        dayOfMonth: 7,
        keywords: ['mercado', 'supermercado', 'carrefour', 'assai', 'atacadao', 'pao de acucar'],
        items: [
          { id: 'item_m1', description: 'Arroz Nobre Tipo 1 (5kg)', quantity: 2, price: 34.00, multiplierWeeks: 1, totalValue: 68.00, realizedValue: 68.00, isFulfilled: true, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
          { id: 'item_m2', description: 'Feijão Carioca Selecionado (1kg)', quantity: 4, price: 8.50, multiplierWeeks: 1, totalValue: 34.00, realizedValue: 34.00, isFulfilled: true, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
          { id: 'item_m3', description: 'Azeite de Oliva Extra Virgem 500ml', quantity: 2, price: 46.00, multiplierWeeks: 1, totalValue: 92.00, realizedValue: 46.00, isFulfilled: false, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
          { id: 'item_m4', description: 'Café Especial Torrado em Grãos (500g)', quantity: 3, price: 28.00, multiplierWeeks: 1, totalValue: 84.00, realizedValue: 84.00, isFulfilled: true, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
          { id: 'item_m5', description: 'Laticínios, Queijos & Manteiga', quantity: 1, price: 160.00, multiplierWeeks: 1, totalValue: 160.00, realizedValue: 160.00, isFulfilled: true, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
          { id: 'item_m6', description: 'Produtos de Limpeza & Higiene Pessoal', quantity: 1, price: 210.00, multiplierWeeks: 1, totalValue: 210.00, realizedValue: 210.00, isFulfilled: true, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
        ],
      },
      {
        id: 'map_feira_semanal',
        name: 'Feira Livre & Hortifrúti (Rotina Semanal)',
        natureId: 'nat_alimentacao',
        applicableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        frequency: 'SEMANAL',
        dayOfWeek: 'Sábado',
        keywords: ['feira', 'hortifruti', 'legumes', 'frutas', 'verduras', 'pastel'],
        items: [
          { id: 'item_f1', description: 'Frutas da Estação (Maçã, Banana, Uva, Mamão)', quantity: 1, price: 65.00, multiplierWeeks: 4, totalValue: 260.00, realizedValue: 65.00, isFulfilled: false, paymentMethod: 'PIX' },
          { id: 'item_f2', description: 'Verduras & Legumes Orgânicos da Semana', quantity: 1, price: 45.00, multiplierWeeks: 4, totalValue: 180.00, realizedValue: 45.00, isFulfilled: false, paymentMethod: 'PIX' },
          { id: 'item_f3', description: 'Ovos Caipiras Orgânicos (Cartela 30 un)', quantity: 1, price: 28.00, multiplierWeeks: 2, totalValue: 56.00, realizedValue: 28.00, isFulfilled: false, paymentMethod: 'PIX' },
        ],
      },
      {
        id: 'map_acougue_proteinas',
        name: 'Açougue & Proteínas Nobres',
        natureId: 'nat_alimentacao',
        applicableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        frequency: 'QUINZENAL',
        dayOfWeek: 'Sábado',
        keywords: ['acougue', 'carnes', 'bife', 'frango', 'swift', 'peixe'],
        items: [
          { id: 'item_p1', description: 'Peito de Frango & Filé de Coxa (kg)', quantity: 4, price: 26.00, multiplierWeeks: 4, totalValue: 416.00, realizedValue: 104.00, isFulfilled: false, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
          { id: 'item_p2', description: 'Carnes Vermelhas de Primeira (Alcatra/Patinho)', quantity: 3, price: 54.00, multiplierWeeks: 2, totalValue: 324.00, realizedValue: 0.00, isFulfilled: false, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
          { id: 'item_p3', description: 'Peixes & Frutos do Mar', quantity: 2, price: 65.00, multiplierWeeks: 1, totalValue: 130.00, realizedValue: 0.00, isFulfilled: false, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
        ],
      },
    ],
  },
  {
    id: 'nat_moradia',
    name: 'Moradia & Condomínio',
    color: '#38BDF8',
    icon: '🏠',
    type: 'FIXA',
    description: 'Custos operacionais e estruturais inegociáveis do imóvel residencial.',
    overCeilingJustification: '',
    justificationHistory: [],
    keywords: ['aluguel', 'condominio', 'luz', 'energia', 'agua', 'gas', 'internet', 'sabesp', 'enel'],
    mappings: [
      {
        id: 'map_moradia_base',
        name: 'Contas Fixas & Estruturais',
        natureId: 'nat_moradia',
        applicableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        dayOfMonth: 10,
        keywords: ['condominio', 'coelba', 'enel', 'luz', 'energia', 'internet', 'fibra', 'gas'],
        items: [
          { id: 'item_m_condo', description: 'Taxa Condominial Residencial', quantity: 1, price: 1250.00, multiplierWeeks: 1, totalValue: 1250.00, realizedValue: 1250.00, isFulfilled: true, paymentMethod: 'BOLETO' },
          { id: 'item_m_energia', description: 'Energia Elétrica Estimada (Coelba)', quantity: 1, price: 420.00, multiplierWeeks: 1, totalValue: 420.00, realizedValue: 420.00, isFulfilled: true, paymentMethod: 'BOLETO' },
          { id: 'item_m_internet', description: 'Internet Fibra Óptica 1Gbps', quantity: 1, price: 180.00, multiplierWeeks: 1, totalValue: 180.00, realizedValue: 180.00, isFulfilled: true, paymentMethod: 'CARTAO', cardName: 'XP Visa Infinite' },
          { id: 'item_m_gas', description: 'Gás Encanado Mensal', quantity: 1, price: 110.00, multiplierWeeks: 1, totalValue: 110.00, realizedValue: 0.00, isFulfilled: false, paymentMethod: 'BOLETO' },
        ],
      },
    ],
  },
  {
    id: 'nat_educacao',
    name: 'Educação & Desenvolvimento',
    color: '#A855F7',
    icon: '🎓',
    type: 'FIXA',
    description: 'Mensalidades escolares e programas contínuos de aprendizado.',
    overCeilingJustification: '',
    justificationHistory: [],
    keywords: ['escola', 'colegio', 'faculdade', 'curso', 'idiomas', 'ingles', 'mensalidade', 'livro'],
    mappings: [
      {
        id: 'map_edu_padrao',
        name: 'Mensalidade & Atividades',
        natureId: 'nat_educacao',
        applicableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        keywords: ['escola', 'colegio', 'mensalidade', 'curso', 'ingles'],
        items: [
          { id: 'item_e_escola', description: 'Mensalidade Escolar dos Filhos', quantity: 1, price: 2850.00, multiplierWeeks: 1, totalValue: 2850.00, realizedValue: 2850.00, isFulfilled: true, paymentMethod: 'BOLETO' },
          { id: 'item_e_ingles', description: 'Curso de Idiomas / Inglês Avançado', quantity: 1, price: 380.00, multiplierWeeks: 1, totalValue: 380.00, realizedValue: 0.00, isFulfilled: false, paymentMethod: 'BOLETO' },
        ],
      },
    ],
  },
  {
    id: 'nat_saude',
    name: 'Saúde & Cuidados',
    color: '#F43F5E',
    icon: '🩺',
    type: 'ESSENCIAL',
    description: 'Planos de saúde familiares, odontologia e farmácia contínua.',
    overCeilingJustification: '',
    justificationHistory: [],
    keywords: ['farmacia', 'drogaria', 'remedio', 'medico', 'consulta', 'exame', 'laboratorio', 'drogasil', 'droga raia', 'plano de saude'],
    mappings: [
      {
        id: 'map_saude_fixo',
        name: 'Cobertura Médica & Medicamentos',
        natureId: 'nat_saude',
        applicableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        keywords: ['plano de saude', 'convenio', 'farmacia', 'drogaria', 'drogasil', 'droga raia', 'remedio'],
        items: [
          { id: 'item_s_plano', description: 'Plano de Saúde Familiar Amplo', quantity: 1, price: 1680.00, multiplierWeeks: 1, totalValue: 1680.00, realizedValue: 1680.00, isFulfilled: true, paymentMethod: 'BOLETO' },
          { id: 'item_s_farmacia', description: 'Farmácia & Suplementação Contínua', quantity: 1, price: 250.00, multiplierWeeks: 1, totalValue: 250.00, realizedValue: 110.00, isFulfilled: false, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
        ],
      },
    ],
  },
  {
    id: 'nat_transporte',
    name: 'Transporte & Mobilidade',
    color: '#F59E0B',
    icon: '🚗',
    type: 'VARIAVEL',
    description: 'Combustível, pedágios, estacionamento e manutenções do veículo.',
    overCeilingJustification: '',
    justificationHistory: [],
    keywords: ['posto', 'gasolina', 'etanol', 'combustivel', 'ipiranga', 'shell', 'uber', '99', 'sem parar', 'conectcar', 'pedagio', 'estacionamento'],
    mappings: [
      {
        id: 'map_transp_semanal',
        name: 'Combustível & Rodagem Semanal',
        natureId: 'nat_transporte',
        applicableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        keywords: ['posto', 'gasolina', 'etanol', 'combustivel', 'ipiranga', 'shell', 'sem parar', 'conectcar', 'pedagio'],
        items: [
          { id: 'item_t_gasolina', description: 'Tanque Gasolina Aditivada (Semanal)', quantity: 1, price: 180.00, multiplierWeeks: 4, totalValue: 720.00, realizedValue: 360.00, isFulfilled: false, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
          { id: 'item_t_pedagio', description: 'Sem Parar / ConectCar Pedágios & Estac.', quantity: 1, price: 120.00, multiplierWeeks: 1, totalValue: 120.00, realizedValue: 95.00, isFulfilled: false, paymentMethod: 'CARTAO', cardName: 'Nubank Mastercard Black' },
        ],
      },
    ],
  },
];
